### ISSUE TITLE
GetDevice on ID3D11Texture2D InvalidCastException

### ISSUE THREAD

**Issue by adstep** [smourier/DirectN#64]
I'm hitting an InvalidCastException when calling GetDevice on ID3D11Texture2D.

Unable to cast COM object of type 'System.__ComObject' to interface type 'DirectN.ID3D11Device'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{DB6F6DDB-AC77-4E88-8253-819DF9BBF140}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).

I converted it to Vortice's implementation via a pointer and it retrieves the device no problem.

```csharp
private static void Process(Direct3D11CaptureFrame frame)
{
    using IComObject<ID3D11Texture2D> capturedTexture = CreateTexture2D(frame.Surface);

    var ptr = capturedTexture.GetInterfacePointer<ID3D11Texture2D>();
    var text = new Vortice.Direct3D11.ID3D11Texture2D(ptr);
    var device = text.Device;

    try
    {
        capturedTexture.Object.GetDevice(out var d3D11Device1);
    }
    catch (Exception ex)
    {
         // InvalidCastException.
    }
```

**Comment by smourier** [comment]
DirectN has two level of API:

* the raw API, interfaces, functions, etc. that are 95% automatically generated (in the _Generated_ and _Manual_ folders)
* extensions API and utilities like IComObject (in _Extensions_ folder), based on the raw API

The raw API is merely bindinds/definitions of the technologies involved (DirectX, DXGI, etc.).
The exensions is useful methods that allows to write more readable, .NET like code. However it's written by hand and only covers small parts of the raw API.

So, DirectN is not a full .NET "wrapper", and it's been designed like this so it looks like original C/C++ code (so existing C/C+ code can more easily be rewritten/ported) and it can be easily maintained on the long run. Note if you're working with .NET core 8, I recommend using DirectNAot instead (https://github.com/smourier/DirectNAot).

So back to your question.

In this case, `GetDevice `is not exposed in the extension API, and you cannot cast (QueryInterface) a texture into a device (this is what you were apparently trying to do). So if your code is like this;

    using IComObject<ID3D11Texture2D> capturedTexture = CreateTexture2D(frame.Surface);

There's currently not an extension that would allow you to do this:

    IComObject<ID3D11Device> device = capturedTexture.GetDevice();

Using the same model as what's found in Extensions folder, these `GetDevice `extensions would be defined as:

        public static IComObject<ID3D11Device> GetDevice(this IComObject<ID3D11DeviceChild> child) => GetDevice<ID3D11Device>(child?.Object);
        public static IComObject<T> GetDevice<T>(this IComObject<ID3D11DeviceChild> child) where T : ID3D11Device => GetDevice<T>(child?.Object);
        public static IComObject<T> GetDevice<T>(this ID3D11DeviceChild child) where T : ID3D11Device
        {
            if (child == null)
                throw new ArgumentNullException(nameof(child));

            child.GetDevice(out var device);
            return new ComObject<T>((T)device);
        }

And I have actually added in the latest commit since it's useful https://github.com/smourier/DirectN/commit/315181e734a9401579a0f6fb211487ce57c6ff6b (PS: anyone can create pull requests on such extensions if they are useful)

So, right now, w/o this extension, you can get a device with this type of code:

    using IComObject<ID3D11Texture2D> capturedTexture = CreateTexture2D(frame.Surface);
    capturedTexture .Object.GetDevice(out var device); // all raw COM objects are accessible with `Object` property

And you have a raw `ID3D11Device `in device. You can create a wrapper around it if you want, but again, it's not strictly necessary:

    using var dev = new ComObject<ID3D11Device>(device);

**Comment by adstep** [comment]
Thanks for the quick reply!

To clarify I am trying to call GetDevice on the texture to get a reference to the device that created it. I am aware that the method is inherited from [ID3D11DeviceChild](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicechild-getdevice).

My issue is not related to confusion about how to call the method. I don't need need an extension for ID3D11Texture2D to call GetDevice. It is already [implemented directly in the interface](https://github.com/smourier/DirectN/blob/315181e734a9401579a0f6fb211487ce57c6ff6b/DirectN/DirectN/Generated/ID3D11Texture2D.cs#L10-L12). When I call this existing method I get a InvalidCastException.

Here's the stack trace:
```
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr& ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at DirectN.ID3D11Texture2D.GetDevice(ID3D11Device& ppDevice)
   at CaptureDemo.Services.CaptureService.ToBitmap(Direct3D11CaptureFrame frame) in C:\dev\apps\capture-demo\src\CaptureDemo\Services\CaptureService.cs:line 103
```

I'll share a demo to repro with you but it'll take me a few minutes.

**Comment by adstep** [comment]
I've creeated a repro with a minimal example.

It has a single test [GetDeviceRepro](https://github.com/adstep/directn-capture-repro/blob/cdaa9c94dc57e8440effac95beaaf45b89c00796/src/CaptureRepro/UnitTests.cs#L12C9-L24C10). Which exercises the code that throws the exception.

The service attempts to setup a FramePool to capture the primary monitor. The exception occurs as we go to process the first [Direct3D11CaptureFrame](https://github.com/adstep/directn-capture-repro/blob/cdaa9c94dc57e8440effac95beaaf45b89c00796/src/CaptureRepro/Services/CaptureService.cs#L76-L77).

**Comment by smourier** [comment]
This has nothing to do with DirectN, which, as explained, consist merely of thin binding/projections/definitions/ABI over DirectX and other technology w/o intelligence (except for some utilities in _Extensions_).

The error is because you can't get the device from a thread that didn't created it, at least in the way your sample is written.

This fails
            framePool.FrameArrived += (s, e) =>
            {
                var frame = framePool.TryGetNextFrame();
                using var tex = CreateTexture2D(frame.Surface);
                tex.Object.GetDevice(out var device);
            };

This works:

            var dq = DispatcherQueue.GetForCurrentThread();
            framePool.FrameArrived += (s, e) =>
            {
                var frame = framePool.TryGetNextFrame();
                dq.TryEnqueue(() =>
                {
                    using var tex = CreateTexture2D(frame.Surface);
                    tex.Object.GetDevice(out var device);
                });
            };
